//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashDownLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableTask
    {
        public long TaskId { get; set; }
        public string Url { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public long FileSize { get; set; }
        public string TempFullName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime FinishTime { get; set; }
        public string Status { get; set; }
        public short Threads { get; set; }
        public string Directory { get; set; }
        public bool IsTrashed { get; set; }
    }
}
